### ISSUE TITLE
Map Design Feedback QoL Changes

### ISSUE THREAD

**Issue by Nodding** [loudsmilestudios/TetraForce#291]
**Description**
Feedback to improve the map design of the over world.

1. Clarifying you can move more to the right on the shore beyond the slime marsh area.
2. Introduce enemy doors more naturally in starting area near slime.

**Comment by IQGobo** [comment]
Some thoughts:

- Starting from the shrine has some disadvantages, like the dark cave, the blast rocks that cannot be removed at the beginning and the long way to town where you could branch off to two other dead ends. I would suggest spawning the player by the lake to the south of the farm and putting a npc there. This way we could give the new player directions, invent some backstory like being pulled out of the water or something, it would be a short way to town and the shrine area would be a bonus for exploration.
- Once the player doesn't start at the shrine anymore, instead of dropping from the high ledge to get to the cemetery area, there should be steps. They could be kept hidden behind some bushes and trees, hard to spot. So adventurous players can get in without bombing the rock at the bridge across the chasm as a secondary entrance.
- Maybe the fenced in area at the farm could be a nice place for a kill all enemies encounter, with the switch to start the fight right in the center. Don't know how the "room" needs to be defined for that.
- Let the townsfolk direct the player to go southeast to the beach, with stories about how the monsters started to appear after some rowdies broke a few planks to get into the old ship that was washed onto the beach many years ago. The players should go investigate and see if they could find something useful.
- Can we do more rocks on the northern cliff side of the upper connector between the ship and town? It could look like a landslide and there could be someone there who tells something about how she keeps an eye on the monsters on the other side and how the rocks that fell down act like a natural barrier to keep them away from townsfolk. Add some moral choice for players: should I blast the rocks and risk endangering the people of Tiskal village or do I take the scenic route all the way to the south once I got the bombs from the ship wreck dungeon? It adds a bit of depth even if there are no actual consequences of using the shortcut.
- There could be a ledge reaching into the big lake to the west with a fisherman, either on the north shore at the maze with slimes and holes, or at the south shore, where there is a small stretch of land you can get to through the cave at the shrine. Just a point of interest, something to make the world more lively.
- On the same note, the garden like area in the center of the beach could belong to a ruined house later on. Maybe an older surfer dude could tell stories about how he used to run the bar there and renting surf boards or something, up until the undead pirates started showing up and raiding the vicinity of the wrecked ship. This could also be part of a series of tradeing quests like in Link's Awakening: talk to the dude, get to know about the hidden area behind the bar, bring back some lost memorabilia that gets traded in for something else another character might find useful elsewhere.

**Comment by Nodding** [comment]
As always IQ I love your perspectives on things. 

- I think it'd be great to have a NPC that introduces the characters to the world and gives them direction, towards the village. I think an effective way to handle this would be a spirit inside the temple warning of the evil in the land, and that they the heroes were resurrected to help stop it. They could also say that the items buried with them were robbed by a thieves clan that reaches wide across the kingdom. 
- The cemetery I agree is a little easy for new players to get into but I like that the only way to get back to the starting shrine area is with bombs, and that it can be explored early for a spirit pearl.
- I like the idea of the farm fight, and I believe that could be done but I would have to have the map infront of me to find where. My main worry with it is that because its so open it'd be hard to fence in the players once it is started.
- The townsfolk definitely need to direct the players more, and I believe @Elginive was planning on this.
- I like the rock slide idea a lot. I wonder how hard it would be to make it where she would react when the rocks are gone, having her dialogue change. 
- The north west area really needs a rework as it is pretty much the last untouched in a while place before the demo is released. Again I believe @Elginive had ideas for what to place in the cave all the way up there.
- A trading quest would be fun I think but also I think that would need to be post demo release. As of now I wanna focus on making whats in the game fun and polishing it up for that.

**Comment by Nodding** [comment]
The NPC ideas specifically tie this into #293

**Comment by IQGobo** [comment]
If we keep the player start in the shrine area, the spirit should accompany the player to Tiskal. Either by teleporting to a new spot in sight and fading before the player reaches it, or by really moving through a way point system, only progressing to the next point if the player is close enough. This would be especially cool, if we could do this while the world is shrouded in twilight, with the spirit acting as a bright beacon to illuminate the vicinity.

The farm fight could take place on the field just west of the red barn. There is a small entrance from the north that is easy to close off once the fight starts and the whole area is enclosed anyways. The fenced area could be increased a bit to the south if it is too confined.

Players can get stuck in the west part of the ship as the push block only moves one tile, trapping the player.

**Comment by Nodding** [comment]
Can you provide the area for the ship where players can get stuck?

As for the spirit idea, I like it, but I don't know if it's something we would do before the demo. I do already have a small fight involving enemy spawning statues right before the village I think will be a nice introduction, although I don't think any newer players have played it yet as it isn't in the current main build.

**Comment by IQGobo** [comment]
![tf_bug_ship_point_of_no_return1](https://user-images.githubusercontent.com/1500105/127969748-577317c4-c6e4-492f-ae5e-0febee54f2ee.png)
![tf_bug_ship_point_of_no_return2](https://user-images.githubusercontent.com/1500105/127969751-ea007688-533a-4060-a7b2-fc11632e44f0.png)
![tf_bug_ship_point_of_no_return3](https://user-images.githubusercontent.com/1500105/127969752-2260ff10-cee8-4be5-8ede-f3edea032e78.png)
Once you go down the ledge from east to west in this room you will be stuck. You cannot climb back up, you cannot push the block more than one tile, there are no bombable places (if you even got the bombs already) and you might even have killed all enemies in the room to the west, so there is no death warping available anymore.

**Comment by Nodding** [comment]
Ah yes this will be fixed. That block will be a statue that can be moved multiple times. Ill see if I can push that change to the map_qol branch tonight.
